### PR TITLE
IfcAlignment support

### PR DESCRIPTION
**Pull request by urosjovanovic**
Hello,

As discussed [here](https://github.com/xBimTeam/XbimEssentials/issues/89#issuecomment-303360307), I'm opening a pull request for support of the [IfcAlignment](http://www.buildingsmart-tech.org/mvd/IFC4x1/Alignment/1.0.1/html/). IfcAlignment is an extension to the IFC 4 schema. The changelog from IFC4 Add1 is avalable [here](http://www.buildingsmart-tech.org/mvd/IFC4x1/Alignment/1.0.1/html/link/ifc4-add1-to-ifc4x1-changelog.htm).

Classes for new entities were made manually (not auto-generated) following the style and logic established by the existing codebase. Minor typos and/or attribute and interface usage errors are possible. Particularly, it was unclear to me when to use the `IContainsEntityReferences` and `IContainsIndexedReference`, as well as the correct usage of EntityAttributeType enum.

Along with the classes, there is an example ifc alignment file and test class added in Unit Tests.

Please note that I am not very well versed in using git, I've created a new branch for this feature so we can further discuss and develop the support for the Alignment schema. Hope that's alright.

Any feedback is welcomed!

Best regards,
Uros

### CODE REVIEW

**Comment by martin1cerny** [comment]
Hi @urosjovanovic , thanks for a good chunk of work on this. My only objection is that this will create the file as `IFC4` schema where EXPRESS definition for IfcAlignment defines complete schema as `IfcAlignment1x1`. Where I don't think that this naming strategy is correct you should know that resulting file will be invalid as IFC4 (containing entities not defined in the actual schema) and won't be recognized as `IfcAlignment1x1` because it won't be reflected in the header. 

You can change the definition in the header from the code but our automated recognition in `IfcStore` won't pick this up and will throw an exception. But you should still be able to use MemoryModel or EsentModel where you specify the `EntityFactory` yourself. 

Where I can see this as a useful tool for testing the schema I'd also like to flag the pitfalls.

**Comment by urosjovanovic** [comment]
Hi @martin1cerny,

Thanks for the feedback. We kinda skipped over the whole writing process, as we only need reading functionality at the moment. Although the schema I've found says it's `IFCALIGNMENT1X1`, the [official BS page](http://www.buildingsmart-tech.org/mvd/IFC4x1/Alignment/1.0.1/html/) says it's actually `IFC4X1` schema with Alignment being MVD. The example files [here](http://www.buildingsmart-tech.org/mvd/IFC4x1/Alignment/1.0.1/html/link/vertical-alignment.htm) reflect that (the header says 'IFC4X1'). There are some official schemas [here ](http://www.buildingsmart-tech.org/ifc/IFC4x1/)as well.

Nevertheless, what is the recommended way to go around this? Should we make a new assembly for IFC4X1? Should a new namespace (Xbim.Ifc4x1) be defined as well? Looking at the code, it seems that doing so would be a considerable amount of work (doing it manually ofc), but maybe I'm being mistaken.

**Comment by martin1cerny** [comment]
I realized that `IFC4x1` was used elsewhere but the same applies. You are right that creating new schema implementation would be overkill as you only need to implement a handful of classes. I'm not sure yet what the best approach would be. I thought about implementing a mechanism in xBIM Essentials to write extensions where this would be a perfect use case. I do have a conceptual plan how to do so and it wouldn't be very hard (few days work) but we don't have any own project which would cover such a development right now. 

If you only need to read the data it should be enough to bypass schema checking and define IFC4 EntityFactory to be used by the IModel implementation.

**Comment by urosjovanovic** [comment]
Hi @martin1cerny ,
As discussed I've created new EntityFactory in Ifc4x1 namespace and adjusted IfcStore accordingly (creation of Esent and Memory Models). Also, I've relocated all IfcAlignment entities into Ifc4x1 namespace as well.

Best regards,
Uros

**Comment by martin1cerny** [comment]
Great work @urosjovanovic !

If you wanted to share any findings and/or experience about `IfcAlignment` I'd be very interested. If it takes off I'll make sure to make it part of the main branch and core release.

Martin

**Comment by jv112602** [comment]
Martin,

Is there any plan to add the ifcAlignment support to the release. The latest versions of the leading civil design packages - AutoCAD Civil3D and Bentley OpenRoads all export IfcAlignment's. I would volunteer some development time if needed to expedite this effort.

thanks

Jay

**Comment by martin1cerny** [comment]
Hi Jay, there is not such a plan at the moment. To my knowledge, it is still an ongoing project which hasn't yet been published as an official schema neither by buildingSMART nor by ISO or CEN. I still can't get to any official EXPRESS schema from buildingSMART website (though MVD documentation is available). Do you have any insights in this?

**Comment by martin1cerny** [comment]
Interesting, I never came across this page on www.buildingsmart-tech.org. It doesn't seem to be linked from the main site. What I would like to see is this link working: http://www.buildingsmart-tech.org/ifc/review/IFC4x1/final/IFC4x1_FINAL.exp 

It is official link from [here](http://www.buildingsmart-tech.org/ifc/IFC4x1/final/html/annex/annex-a.htm) and it should contain official schema definition as computer interpretable EXPRESS schema like [this one for IFC4 Add2](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/IFC4_ADD2.exp). This is what we use for code generation. I can also use it for automated schema comparison to identify all changes between any other IFC version to learn the differences in a reliable way. 

I tried to ask buildingSMART to fix the issue with EXPRESS schema availability but I didn't get any reply. While it might look stupid to insist on official release of the complete schema definition I see it as a real issue. I've seen several unofficial EXPRESS schemas for IfcAlignment/IFC4x1 but they all use different schema identifier compared to examples in the [official documentation](http://www.buildingsmart-tech.org/mvd/IFC4x1/Alignment/1.0/html/link/annex-e.htm). And that is something which has to be absolutely clear because we use it to select the right early binding schema implementation. Further more, if the identifier stays *'IFC4'* we could easily just extend IFC4Add1 to IFC4x1 and everything would just work. It would actually be my preferred option. But I don't want to invest any time in it unless this is clear from the documentation and official complete schema release.

**Comment by martin1cerny** [comment]
BTW: The schema you are pointing to is just one-of possible schema implementations (like implementations in xBIM) but not the definition.

**Comment by martin1cerny** [comment]
Thank you very much. I missed this link completely because links I refer to work in all IFC4 releases and IFC2x3. It will take me some time to make it a proper part of our code generation routines because it will require changes in schema resolution. Also, I will have to implement XML related conventions and schema resolution because this is new XML namespace and configuration. I kind of hope it will settle down for several years at some point like IFC2x3 did. People will otherwise hesitate to adopt IFC4 when it doesn't feel stable (also changes are minor).

**Comment by martin1cerny** [comment]
Hi @jv112602 , I finally found some time to work on this. I'm sorry not to use your work, but it is better for us to have IFC Alignment put in as a part of our code generation. So, it is in 7c83f00eb4299b96e88cb4e46dc3bc958cf3875e now. Thank you very much for a highly valuable input.

I suppose you already have some code using this alongside with some more complex testing data. Can you try to switch to my implementation to see if it all works as expected? I'd appreciate any feedback.

XML for IFC Alignment is not yet fully supported because namespaces on the buildingSMART website keep changing. I checked three times in last month and I think I saw all kinds of mismatches. Some resources previously available are not there at all etc. I'll implement it once it settles down.

**Comment by martin1cerny** [comment]
BTW: NuGet package: 4.0.30-V010

**Comment by martin1cerny** [comment]
Interesting enough, while I did some further work on this, buildingSMART website got updated with new documentation silently. That includes new example files and other changes. I just updated the code to reflect this. I wonder now which version is implemented/supported in AutoCAD Civil3D and Bentley OpenRoads. @urosjovanovic  - would you have any real world files to share?

**Comment by jv112602** [comment]
Here is a file i created from open roads
[Ramp C.zip](https://github.com/xBimTeam/XbimEssentials/files/1955406/Ramp.C.zip)

**Comment by martin1cerny** [comment]
Right, this is a bad new. This file implements IFC4x1 RC1 which is two years old and not binary compatible with IFC4x1 FINAL because tome types and attributes were changed radically between RC releases. Plus this claims to be IFC4 in the header which it is not. Too bad. I think I'll park this for now.

**Comment by martin1cerny** [comment]
It was IFC4x1 RC1 a weak and a day ago and it is IFC4x1 FINAL now. If you get the latest `develop` branch of xBIM Essentials you will find these testing files [here](https://github.com/xBimTeam/XbimEssentials/tree/develop/Xbim.Essentials.Tests/TestSourceFiles/Alignment). If you browse the history you will find the original ones. The FINAL files work with the latest implementation.

The file you sent is also IFC4x1 RC1 from what I can see.

**Comment by Tpullmann** [comment]
Thanks a lot. 
I used the latest develop branch, and really I can import IFC4X1 and see the alignment elements semantically including their properties. 
Nevertheless the productd WexBIM File (or the WebGL rendering part) does not contain the alignment path. Is that feature planned, or is it up to me to generate the curves if I want to see them?

**Comment by martin1cerny** [comment]
Generating the geometry is all done in xBIM Geometry project. That is responsible for generation of the triangulated geometry for visualization. So, while xBIM Essentials reads all the data and makes it accessible, geometry engine doesn't implement new curves and geometries defined in the IFC Alignment extension. [Here](https://github.com/xBimTeam/XbimGeometry/issues/106) is the list of classes which need to be implemented in the engine to allow complete visualization. Any contribution in this direction would be greatly appreciated.

**Pull request closed without merging**
