### PR TITLE
[FIXED] Fix duplicate IFCORGANIZATION creation during model Create process with xBimCredentials.

### PR DESCRIPTION
**Pull request by liszto**

### CODE REVIEW

**Comment by martin1cerny** [comment]
The code checking for the existing organization doesn't check the name of the organization. So, if the code is used while editing existing model owner history will be created pointing to wrong organization. Can you fix this minor issue please?

**Comment by liszto** [comment]
Ok I will !

**Comment by martin1cerny** [comment]
Thank you for your contribution @liszto!

**Comment by liszto** [comment]
I updated and I fixed another issue that I forget to mention in my commit.
In the `DefaultOwningUser` method you used `_editorDetails.EditorsOrganisationName` whereas in `DefaultOwningApplication` you were using `_editorDetails.ApplicationDevelopersName`. It must be the DefaultOwning in both cases right ?

**Pull request merged**
