### PR TITLE
Fix for large coordinate system

### PR DESCRIPTION
**Pull request by fomayette**
Still WIP, @andyward suggested I create the pull request early to ease collaboration

### CODE REVIEW

**Comment by andyward** [comment]
Hi @fomayette , do you have a test case for this you can share? (I'm aware of the railway line one from your client). However we tackle this, it would be good to have a suitable stripped down test model to validate any fix.

**Comment by fomayette** [comment]
I'm using the railway model as well for debugging.  I guess I could write up an IFC by hand, with a simple model with huge offset, but I get the feeling you guys could achieve that faster.

**Comment by andyward** [comment]
Thanks for confirming Francois. Just wanted to be sure on the exact issue you were looking to resolve.

**Comment by andyward** [comment]
Closing - Fixed inhttps://github.com/xBimTeam/XbimEssentials/commit/2b6272cb513bbbaf51f3b710057cfd3c02b8ad7c

**Pull request closed without merging**
