### PR TITLE
Fix for ifcxml if RelatedObjects is Empty Element

### PR DESCRIPTION
**Pull request by imsmk**
fix for #187 

fix for parsing ifcxml, if model is ifc4 (not add1 or add2), which contains RelatedObjects as an empty element with type definition.

### CODE REVIEW

**Comment by martin1cerny** [comment]
I don't think this is the right condition. Element might well not be empty and might be defined there as a complete definition rather than just an empty pointer to object defined elsewhere.

**Comment by imsmk** [comment]
I think non empty enumeration elements are handled correct by xbimxmlreader.
I had hoped that the only case is empty enumerable element with type definition.
Can you point in the right direction? Do you have some negative ifcxml snippet?
Thanks

**Comment by martin1cerny** [comment]
I'm only guessing based on your example. Partial example might look like this [handcrafted]:

```xml
<IfcRelDefinesByProperties id="x3">
  <RelatedObjects xsi:type="IfcSite" id="s1" 
    GlobalId="1lOEDpLKz62xrR7$RUqRl$" 
    Name="Default site">
    <OwnerHistory ref="i2" xsi:type="IfcOwnerHistory" xsi:nil="true" />
    <SiteAddress id="i26" xsi:type="IfcPostalAddress" 
      Purpose="site" 
      Town="Newcastle upon Tyne" 
      Region="Tyne and Wear" PostalCode="NE6 2SY" Country="United Kingdom" />
  </RelatedObjects>
  <RelatingPropertyDefinition>
    <IfcElementQuantity xsi:nil="true" ref="x2"/>
  </RelatingPropertyDefinition>
</IfcRelDefinesByProperties>
```

**Comment by imsmk** [comment]
I see.
so it's enough to add
``(typeof(IEnumerable).IsAssignableFrom(type) && input.GetAttribute("type",_xsi)!=null)
``
am I miss something else ?

**Comment by martin1cerny** [comment]
That should hopefully work.

**Comment by martin1cerny** [comment]
Than you very much for your contribution!

**Pull request merged**
