### PR TITLE
Add a few tests for develop version

### PR DESCRIPTION
**Pull request by kozintsev**
I tested the xBIM Toolkit in several medium and large models.
And I found a few problems. You can see my tests.
I hope it will be useful for the development of the xBIM toolkit.

### CODE REVIEW

**Comment by martin1cerny** [comment]
Hi @kozintsev , it would be useful if you could describe the problems here before we start digging into the tests and code.

**Comment by kozintsev** [comment]
@martin1cerny Ok. I created Issues with describe the problem.

**Comment by martin1cerny** [comment]
You can describe it here. That's why this thread exists.

**Comment by kozintsev** [comment]
The model is not broken, but when copying entities target file are obtained is not exactly like a copy a source file.

**Comment by martin1cerny** [comment]
That's quite possible. It might have lines in different order and some floating point numbers may have different fractions at the end because of the precision.

**Comment by kozintsev** [comment]
When saving IFC file has not been sorted EntityLabel attribute.
Therefore, the comparison did not work (FileCompare method  in ModelFilterTest.cs).
I fix it.

**Comment by martin1cerny** [comment]
It is not a requirement to keep objects in order. So you have fixed something which is not a bug and it would have serious performance impact as large files tend to have several millions of entities thus sorting them would take considerable time and other resources.

**Comment by kozintsev** [comment]
Probably you're right, but then need other tests.

**Comment by martin1cerny** [comment]
Yes, but that is very different to what you've requested to pull. I'm happy to merge in enhanced tests which will be tolerant to order of lines in the file.

**Pull request closed without merging**
