### PR TITLE
Added nested list support when get referring types.

### PR DESCRIPTION
**Pull request by youshengCode**
Fix for issue 384. 

https://github.com/xBimTeam/XbimEssentials/issues/384

### CODE REVIEW

**Comment by martin1cerny** [comment]
Thank you for your contribution. It is very much appreciated. Could you also add a test to confirm the functionality and to make sure that it is not broken by any future development or refactoring?

**Comment by youshengCode** [comment]
Sure, currently I'm digging in different schema, seems there is no need to consider the nested list props in IFC2x3, cause the IfcBSplineSurface doesn't exist in IFC2x3. So in another hand, it might slow down the performance of the IFC2x3 schema. I will try to make this schema specific later and add a test too.

I will keep you informed.

**Comment by martin1cerny** [comment]
You don't need to worry about the performance on IFC2x3 models. This code only runs once per type and the mapping is cached. So, the performance hit will be almost nothing. Time consuming part is actual model traversing and that won't be affected by your change.

**Comment by youshengCode** [comment]
Hi Martin, Finally I got some time to finish this.

I pushed 3 tests method for 3 types of properties, single, list, nested list. All passed on my machine.

And the adaptation below, I mentioned in this https://github.com/xBimTeam/XbimEssentials/issues/384#issuecomment-859947388 is also completed and tested.

> I have only updated the *GetReferingTypes(IModel model, Type entityType)* and *ReplaceReferences<TEntity, TReplacement>(IModel model, IEnumerable entities, ReferingType referingType, TReplacement replacement)* these two methods mentioned above.
>
> **Since I am not very familiar with the whole project, this needs to be further adapted in other related methods.**

It works fine for another *ReplaceReferences* now, no need for further adaptation.

By the way, In the method ReplaceReferences for a single entity, I have extracted the part of FallBackOperation as a local method. But I don't know if there is a need to add this FallBackOperation in the nested list loop [here](https://github.com/youshengCode/XbimEssentials/blob/927e1524e8ba69809341582c9d6b14fd202236be/Xbim.Common/ModelHelper.cs#L224), cause it's possible one point can be used more than one time in a nested list entity. Please let me know if this is correct.

**Comment by martin1cerny** [comment]
Hi @youshengCode , thank you for a valuable contribution to the project. It is much appreciated! 

I don't think the `FallBackOperation` needs to be implemented for nested lists. In fact, it should not be needed at all. It is there just as a sanity option.

**Comment by youshengCode** [comment]
Glad that I could help too ; )

That's what I thought, seems there is no need for `FallBackOperation` in the nested list. Thanks for all your help too.

Keep going, have a good day.

**Pull request merged**
