### PR TITLE
Fix "SaveAs" does not set the variable "FileName"

### PR DESCRIPTION
**Pull request by liszto**

### CODE REVIEW

**Comment by liszto** [comment]
Is there a way to create a cleaner "PR" without all my previous changes that I reverted in my master branch ? 
That are still present in my PR changlog... (definietly not clean)

**Comment by martin1cerny** [comment]
It should be possible to squash the commits: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by martin1cerny** [comment]
Or it might be easier to start a new branch which diverges from the current version of xBIM.

**Comment by liszto** [comment]
I will do that cause in my master I push the previous commit and I update mine with your new master so my modification are integrate in the flow with yours.

I will create a branch before all my commit and merged your master into this one. Then create a clean PR based on this one if you prefer. At least the commit stack will be cleaner.

**Pull request closed without merging**
