### PR TITLE
Added in a fix for World Coord data not being stored correctly

### PR DESCRIPTION
**Pull request by LloydPickering**
Holding off merge until I talk to others as it breaks the existing database schema in its current form.

### CODE REVIEW

**Comment by martin1cerny** [comment]
You could check the length of array to see if it contains WCS or not (there is a count as the very first thing and structure has fixed length). That would keep it working for old files. 

I wonder where it got lost...

**Comment by martin1cerny** [comment]
I thought you would put *another* value in which would indicate the version (-2 now). Making just the count negative doesn't allow for the specific version detection in the future.

**Comment by LloydPickering** [comment]
@martin1cerny ah ok, I understand. I'll go back and do that.

**Comment by LloydPickering** [comment]
@martin1cerny how does that look now?

**Comment by LloydPickering** [comment]
I've added in a version property in the Region object. I have marked it as obsolete as when Xbim 4.1 is ready it will mitigate the need to hack around old versions of region data, and property can be removed. I'm going to merge this in now. Any future changes can be made in develop.

**Pull request merged**
